using System.Xml.Linq;
using OpenEC.Monitor.Eni;
using OpenEC.Monitor.Protocol;

namespace OpenEC.Monitor.Learning;

/// <summary>Serialises a configuration as ENI XML in the subset
/// <see cref="EniConfiguration.Load(string)"/> reads back. Learned configurations therefore
/// interoperate with the existing --eni flag, and the same writer serves as the cache
/// format in the integration milestone.</summary>
public static class EniXmlWriter
{
    public static void Write(EniConfiguration configuration, string path) =>
        ToXml(configuration).Save(path);

    public static XDocument ToXml(EniConfiguration configuration) =>
        new(new XElement("EtherCATConfig",
            new XComment(" Generated by OpenEC learning mode from observed bus traffic. "),
            new XElement("Config",
                new XElement("Master",
                    new XElement("Info", new XElement("Name", "EtherCAT Master"))),
                configuration.Slaves.Select(Slave),
                Cyclic(configuration),
                ProcessImage(configuration))));

    private static XElement Slave(EniSlave slave)
    {
        var element = new XElement("Slave",
            new XElement("Info",
                new XElement("Name", slave.Name),
                new XElement("PhysAddr", slave.PhysAddr),
                new XElement("AutoIncAddr", slave.AutoIncAddr),
                new XElement("VendorId", slave.VendorId),
                new XElement("ProductCode", slave.ProductCode),
                new XElement("RevisionNo", slave.RevisionNo)));
        var mailbox = new XElement("Mailbox");
        if (slave.MailboxOut is { } send)
            mailbox.Add(new XElement("Send",
                new XElement("Start", send.Start), new XElement("Length", send.Length)));
        if (slave.MailboxIn is { } recv)
            mailbox.Add(new XElement("Recv",
                new XElement("Start", recv.Start), new XElement("Length", recv.Length)));
        if (mailbox.HasElements) element.Add(mailbox);
        // Written as a numeric port rather than a letter: the letter mapping is unverified
        // (topology design spec §10), and the parser accepts both, so the export stays readable
        // by our own loader without asserting a mapping we have not confirmed.
        if (slave.PreviousPort is { } previous)
            element.Add(new XElement("PreviousPort",
                new XElement("PhysAddr", previous.PhysAddr),
                new XElement("Port", previous.Port)));
        return element;
    }

    /// <summary>Emits `&lt;Cyclic&gt;&lt;Frame&gt;&lt;Cmd&gt;…`, matching the real ENI layout in
    /// `tests/OpenEC.Monitor.Tests/Fixtures/sample.eni.xml`. The parser would accept a flatter
    /// shape (it searches descendants), but the export's purpose is an ENI other tooling can
    /// read, and it doubles as the integration milestone's cache format.</summary>
    private static XElement Cyclic(EniConfiguration configuration)
    {
        var cyclic = new XElement("Cyclic");
        if (configuration.CycleTimeMicroseconds is { } cycleTime)
            cyclic.Add(new XElement("CycleTime", cycleTime));
        var frame = new XElement("Frame");
        cyclic.Add(frame);
        foreach (var command in configuration.CyclicCommands)
        {
            var element = new XElement("Cmd",
                new XElement("Cmd", (int)command.Command),
                new XElement("DataLength", command.DataLength),
                new XElement("Cnt", command.ExpectedWkc));
            if (IsLogical(command.Command))
                element.Add(new XElement("Addr", command.RawAddress));
            else
            {
                element.Add(new XElement("Adp", (ushort)(command.RawAddress & 0xFFFF)));
                element.Add(new XElement("Ado", (ushort)(command.RawAddress >> 16)));
            }
            if (command.InputOffs is { } inputOffs)
                element.Add(new XElement("InputOffs", inputOffs));
            if (command.OutputOffs is { } outputOffs)
                element.Add(new XElement("OutputOffs", outputOffs));
            frame.Add(element);
        }
        return cyclic;
    }

    private static XElement ProcessImage(EniConfiguration configuration) =>
        new("ProcessImage",
            new XElement("Inputs", configuration.Variables.Where(v => v.IsInput).Select(Variable)),
            new XElement("Outputs", configuration.Variables.Where(v => !v.IsInput).Select(Variable)));

    private static XElement Variable(EniVariable variable) =>
        new("Variable",
            new XElement("Name", variable.Name),
            new XElement("DataType", variable.DataType),
            new XElement("BitSize", variable.BitSize),
            new XElement("BitOffs", variable.BitOffs));

    private static bool IsLogical(EtherCatCommand command) =>
        command is EtherCatCommand.Lrd or EtherCatCommand.Lwr or EtherCatCommand.Lrw;
}
