<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpenEC.Monitor\OpenEC.Monitor.csproj" />
    <ProjectReference Include="..\OpenEC.Monitor.Ads\OpenEC.Monitor.Ads.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenEC.Monitor.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>openec</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
